# .circleci/config.yml

version: 2.1
orbs:
  cypress: cypress-io/cypress@7.1.0
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run lint
      - run: npm test:e2e
workflows:
  version: 2.1
  build:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - develop
